# Use postgres/example user/password credentials
version: '3.9'

services:

  db:
    image: postgres
    restart: always
    network_mode: bridge
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: suriya
      POSTGRES_PASSWORD: example
      POSTGRES_DB: inventory

  adminer:
    image: adminer
    network_mode: bridge
    restart: always
    ports:
      - 8080:8080

networks:
  bridge:
    driver: bridge
