# to force cache_web rebuild for any code change
# docker-compose up -d --no-deps --build cache_web
services:
  # This is the sample inventory web spring boot app
  cache_web:
    build:
      # place it within the spring boot app dir - to build from the app's dockerfile
      context: ./
      dockerfile: Dockerfile
    networks:
      - infra_nw_exposed
    container_name: inventory
    hostname: inventory
    restart: on-failure
    # port as in host:container
    ports:
      - "8080:8080"
    depends_on:
      postgres_db:
        condition: service_started
        restart: true
      pgadmin:
        condition: service_started
  # this is postgres db
  postgres_db:
    image: postgres:14.13-alpine3.20
    networks:
      - infra_nw_exposed
    container_name: pgdb
    hostname: postgresdb
    restart: always
    ports:
      - "5432:5432"
    environment:
#      - POSTGRES_DB=one
#      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
    volumes:
      - postgres_db_data:/var/lib/postgresql/data
  # runs admin console to view, monitor the postgres_db
  pgadmin:
    image: dpage/pgadmin4:8.11.0
    networks:
      - infra_nw_exposed
    container_name: pgadmin4
    hostname: dbconsole
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: contact@suriyaprakhash.com
      PGADMIN_DEFAULT_PASSWORD: test
    volumes:
      - pgadmin_data:/var/lib/pgadmin

# this volume is mapped inside the Docker WSL's filesystem
volumes:
  postgres_db_data:
    external: false
  pgadmin_data:
    external: false

# this creates own subnet 172.18.0.x instead of the default 172.17.0.x which is default docker bridge network
networks:
  infra_nw_internal:
    # this network is only visible within the docker containers not to the host machine
    internal: true
    # the nw lifecycle is not maintained outside - meaning the nw will be created/deleted w.r.t this file
    external: false
    driver: bridge
  infra_nw_exposed:
    # this network is exposed to the host machine
    internal: false
    # the nw lifecycle is not maintained outside - meaning the nw will be created/deleted w.r.t this file
    external: false
    driver: bridge

